version: '3.8'

services:
  # MQTT Broker
  mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    container_name: mqtt-broker
    hostname: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    command: >
      sh -c "echo 'listener 1883' > /mosquitto/config/mosquitto.conf &&
             echo 'allow_anonymous true' >> /mosquitto/config/mosquitto.conf &&
             mosquitto -c /mosquitto/config/mosquitto.conf -v"
    networks:
      - ota-network

  # OTA Update Server
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: ota-server
    hostname: ota-server
    ports:
      - "8443:8443"
    environment:
      - MQTT_BROKER_URL=tcp://mqtt-broker:1883
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    networks:
      - ota-network

networks:
  ota-network:
    driver: bridge