# Server configuration
server:
  port: 8443

# Spring basic configuration
spring:
  application:
    name: ota-update-server

# MQTT configuration
mqtt:
  broker:
    url: tcp://mqtt-broker:1883
  request:
    topic: ota/request
  updates:
    topic: ota/updates

# OTA update configuration
ota:
  firmware:
    path: /app/firmware-update.txt