# Server application configuration
server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${KEYSTORE_PATH:certs/server.p12}
    key-store-password: ${KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: server
    trust-store: ${TRUSTSTORE_PATH:certs/truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:changeit}
    trust-store-type: PKCS12
    client-auth: need # Require client certificate authentication

# Spring configuration
spring:
  application:
    name: ota-update-server
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# MQTT configuration
mqtt:
  broker:
    url: ssl://localhost:8883
  client:
    id: server-
  request:
    topic: ota/request
  updates:
    topic: ota/updates

# OTA update configuration
ota:
  firmware:
    path: ${FIRMWARE_PATH:server/src/main/resources/firmware-update.txt}