# Client configuration
server:
  port: 8080

# Spring basic configuration
spring:
  application:
    name: ota-update-client

# MQTT configuration
mqtt:
  broker:
    url: tcp://mqtt-broker:1883
  request:
    topic: ota/request
  updates:
    topic: ota/updates

client:
  device:
    id: client-1

  firmware:
    version: 1.0.0
    output-dir: /firmware